In [2]:
from pathlib import Path
import pandas as pd

In [14]:
file = Path('data/tweets/trumpdb.csv')
df = pd.read_csv(file)
df = df.rename(columns={'created_at':'Date', 'retweet_count': 'number_of_shares', 'favorite_count': 'number_of_likes', 'text':'content'})
df['author'] = ['Trump'] * df.shape[0]
df = df[['Date', 'author', 'content', 'number_of_likes', 'number_of_shares']]
df['Date'] = pd.to_datetime(df['Date'], errors='coerce', format='%m-%d-%Y %H:%M:%S')
df = df.sort_values(by='Date')
df = df.reset_index(drop=True)
df = df.fillna(0).astype({'number_of_shares': 'int64'})
df.to_csv(Path('data/in/twitter/Trump.csv'), index=False)
df

,Date,author,content,number_of_likes,number_of_shares
0,2009-05-04 18:54:25,Trump,Be sure to tune in and watch Donald Trump on L...,202,253
1,2009-05-05 01:00:10,Trump,Donald Trump will be appearing on The View tom...,3,2
2,2009-05-08 13:38:08,Trump,Donald Trump reads Top Ten Financial Tips on L...,2,3
3,2009-05-08 20:40:15,Trump,New Blog Post: Celebrity Apprentice Finale and...,27,8
4,2009-05-12 14:07:28,Trump,My persona will never be that of a wallflower ...,1950,1421
...,...,...,...,...,...
39511,0,Trump,http://goo.gl/AMNEE Countdown to @AmericaNowRa...,0,0
39512,0,Trump,08-09-2011 19:33:31,false,3
39513,0,Trump,http://bit.ly/pwgGsQ,0,0
39514,0,Trump,0,0,0
39515,0,Trump,08-02-2011 19:56:31,false,12